services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kittemplate-app
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8080:8080"
      - "8010:8010"
    volumes:
      - .:/go/src/github.com/dohernandez/kit-template
      - /tmp/go-build:/root/.cache/go-build
    depends_on:
      database:
        condition: service_healthy
    profiles: [ "app" ]

  database-migrate:
    image: migrate/migrate
    container_name: kittemplate-database-migrate
    volumes:
      - ./resources/migrations:/resources/migrations
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    command:
      - "-database"
      - "postgres://kittemplate:kittemplate@database:5432/kittemplate?sslmode=disable"
      - "-path"
      - "/resources/migrations"
      - "up"
    profiles: [ "integration-test", "app" ]

  database:
    image: postgres:17.2-alpine
    container_name: kittemplate-database
    restart: always
    environment:
      POSTGRES_PASSWORD: kittemplate
      POSTGRES_USER: kittemplate
      POSTGRES_DB: kittemplate
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 20s
      retries: 5
      start_period: 3s
    profiles: [ "integration-test", "app" ]
