services:
  database-migrate:
    image: migrate/migrate
    container_name: kittemplate-database-migrate
    volumes:
      - ./resources/migrations:/resources/migrations
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    command:
      - "-database"
      - "postgres://kittemplate:kittemplate@database:5432/kittemplate?sslmode=disable"
      - "-path"
      - "/resources/migrations"
      - "up"

  database:
    image: postgres:17.2-alpine
    container_name: kittemplate-database
    restart: always
    environment:
      POSTGRES_PASSWORD: kittemplate
      POSTGRES_USER: kittemplate
      POSTGRES_DB: kittemplate
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 30s
      retries: 10
      start_period: 5s
